"""Clinician routes — profile, patient list, dashboard, deep dive, SOAP notes.

All endpoints require authentication as a clinician.

New in Phase 6:
    GET  /me/dashboard                                   — Risk Radar
    GET  /me/patients/{id}/risk                          — Single-patient Risk Radar card
    GET  /me/patients/{id}/deep-dive                     — Patient Deep Dive
    POST /me/patients/{id}/soap-note                     — Generate SOAP note
    POST /me/patients/{id}/obligations                   — Set patient obligation
    POST /me/patients/{id}/documents/{doc_id}/annotate   — Save doc annotation
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from supabase import Client

from app.core.security import require_role
from app.db.connection import get_db
from app.middleware.rate_limit import soap_note_rate_limiter
from app.models.auth import CurrentUser
from app.models.clinician import ClinicianRead, ClinicianUpdate
from app.models.dashboard import (
    A2ATimelineResponse,
    AnnotationCreate,
    AnnotationSaveResponse,
    DashboardResponse,
    DashboardSortBy,
    DashboardSortOrder,
    DocumentReviewActionRequest,
    DocumentReviewActionResponse,
    DocumentReviewQueueItem,
    ObligationSetRequest,
    PatientDeepDive,
    PatientRiskData,
    RiskLevel,
    SoapNoteGenerationResponse,
    SoapNoteRequest,
)
from app.models.invite import (
    CurrentInviteCodeResponse,
    InviteCodeGenerateResponse,
    InviteCodeListResponse,
    InviteCodeRevokeResponse,
)
from app.models.obligation import ObligationRead
from app.models.patient import PatientRead
from app.services.clinician_service import ClinicianService

router = APIRouter()

_clinician_dep = require_role("clinician")


def _get_service(db: Client = Depends(get_db)) -> ClinicianService:
    return ClinicianService(db)


# ── Existing endpoints ───────────────────────────────────────────────────────


@router.get("/me", response_model=ClinicianRead, summary="Get my clinician profile")
async def get_my_profile(
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.get_profile(user.id)


@router.put("/me", response_model=ClinicianRead, summary="Update my clinician profile")
async def update_my_profile(
    data: ClinicianUpdate,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.update_profile(user.id, data.model_dump(exclude_unset=True))


@router.get(
    "/me/patients",
    summary="List my assigned patients",
    description="Returns all patients with an active care_team relationship.",
)
async def get_my_patients(
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.get_patients(user.id)


@router.get(
    "/me/patients/{patient_id}",
    response_model=PatientRead,
    summary="Get patient detail",
    description="Only accessible if you have an active care team assignment.",
)
async def get_patient_detail(
    patient_id: UUID,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.get_patient_detail(user.id, patient_id)


@router.post(
    "/me/invite-code",
    response_model=InviteCodeGenerateResponse,
    summary="Generate a patient invite code",
    description="Creates a pending care_team row. Share the code with a patient.",
)
async def generate_invite_code(
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> InviteCodeGenerateResponse:
    payload = await service.generate_invite_code(user.id)
    return InviteCodeGenerateResponse.model_validate(payload)


@router.get(
    "/me/invite-code",
    response_model=CurrentInviteCodeResponse,
    summary="Get current patient invite code",
    description="Returns the latest pending patient invite code for this clinician, if one exists.",
)
async def get_current_invite_code(
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> CurrentInviteCodeResponse:
    payload = await service.get_current_invite_code(user.id)
    return CurrentInviteCodeResponse.model_validate(payload)


@router.get(
    "/me/invite-codes",
    response_model=InviteCodeListResponse,
    summary="List patient invite codes",
    description=(
        "Returns active, claimed, and inactive invite codes generated by this clinician "
        "for patient onboarding and audit visibility."
    ),
)
async def list_invite_codes(
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> InviteCodeListResponse:
    payload = await service.list_invite_codes(user.id)
    return InviteCodeListResponse.model_validate(payload)


@router.post(
    "/me/invite-codes/{care_team_id}/revoke",
    response_model=InviteCodeRevokeResponse,
    summary="Revoke a pending patient invite code",
    description="Marks a pending unclaimed invite code as inactive.",
)
async def revoke_invite_code(
    care_team_id: UUID,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> InviteCodeRevokeResponse:
    payload = await service.revoke_invite_code(user.id, care_team_id)
    return InviteCodeRevokeResponse.model_validate(payload)


# ── Phase 6 endpoints ────────────────────────────────────────────────────────


@router.get(
    "/me/document-review-queue",
    response_model=list[DocumentReviewQueueItem],
    summary="List pending patient-uploaded documents for review",
    description=(
        "Returns pending patient-uploaded documents for patients currently assigned "
        "to the authenticated clinician."
    ),
)
async def get_document_review_queue(
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.list_document_review_queue(user.id)


@router.post(
    "/me/patients/{patient_id}/documents/{document_id}/approve",
    response_model=DocumentReviewActionResponse,
    summary="Approve a pending patient-uploaded document",
)
async def approve_document_review(
    patient_id: UUID,
    document_id: UUID,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.approve_document_review(user.id, patient_id, document_id)


@router.post(
    "/me/patients/{patient_id}/documents/{document_id}/reject",
    response_model=DocumentReviewActionResponse,
    summary="Reject a pending patient-uploaded document",
)
async def reject_document_review(
    patient_id: UUID,
    document_id: UUID,
    request: DocumentReviewActionRequest,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    return await service.reject_document_review(
        user.id,
        patient_id,
        document_id,
        request.review_note,
    )


@router.get(
    "/me/dashboard",
    response_model=DashboardResponse,
    summary="Risk Radar — clinician dashboard",
    description=(
        "Returns risk level, adherence score, ADR count, and last activity "
        "for all assigned patients. Sorted by risk (high first)."
    ),
)
async def get_dashboard(
    sort_by: DashboardSortBy = Query(default="risk"),
    sort_order: DashboardSortOrder = Query(default="desc"),
    risk_filter: RiskLevel | None = Query(default=None),
    min_med_count: int | None = Query(default=None, ge=0),
    max_last_activity_days: int | None = Query(default=None, ge=0),
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=50, ge=1, le=100),
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    """GET /api/v1/clinicians/me/dashboard

    Risk Radar endpoint — see DashboardResponse model.
    """
    return await service.get_dashboard_data(
        user.id,
        sort_by=sort_by,
        sort_order=sort_order,
        risk_filter=risk_filter,
        min_med_count=min_med_count,
        max_last_activity_days=max_last_activity_days,
        page=page,
        page_size=page_size,
    )


@router.get(
    "/me/patients/{patient_id}/risk",
    response_model=PatientRiskData,
    summary="Patient Risk Radar snapshot",
    description="Returns the latest risk card payload for one assigned patient.",
)
async def get_patient_risk_snapshot(
    patient_id: UUID,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    """GET /api/v1/clinicians/me/patients/{patient_id}/risk"""
    return await service.get_patient_risk_snapshot(user.id, patient_id)


@router.get(
    "/me/patients/{patient_id}/deep-dive",
    response_model=PatientDeepDive,
    summary="Patient Deep Dive — full aggregated view",
    description=(
        "Returns demographics, active medications, 30-day adherence series, "
        "symptom reports, chat transcript, conditions, allergies, documents, "
        "and the latest AI-generated SOAP note."
    ),
)
async def get_patient_deep_dive(
    patient_id: UUID,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    """GET /api/v1/clinicians/me/patients/{patient_id}/deep-dive"""
    return await service.get_patient_deep_dive(user.id, patient_id)


@router.get(
    "/me/patients/{patient_id}/a2a-timeline",
    response_model=A2ATimelineResponse,
    summary="Patient A2A lifecycle timeline",
    description=(
        "Returns A2A delegation task timeline for a patient, "
        "optionally filtered by chat session_id."
    ),
)
async def get_patient_a2a_timeline(
    patient_id: UUID,
    session_id: str | None = Query(default=None),
    limit: int = Query(default=50, ge=1, le=200),
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    """GET /api/v1/clinicians/me/patients/{patient_id}/a2a-timeline"""
    return await service.get_patient_a2a_timeline(
        user.id,
        patient_id,
        session_id=session_id,
        limit=limit,
    )


@router.post(
    "/me/patients/{patient_id}/soap-note",
    response_model=SoapNoteGenerationResponse,
    summary="Generate AI SOAP note",
    description=(
        "Triggers the LangGraph Summarization Agent (Gemini 3.1 Pro Preview) "
        "to generate a SOAP note from patient data. Stores result in soap_notes table. "
        "Note: this may take 15-30 seconds."
    ),
)
async def generate_soap_note(
    patient_id: UUID,
    request: SoapNoteRequest,
    db: Client = Depends(get_db),
    user: CurrentUser = Depends(_clinician_dep),
) -> Any:
    """POST /api/v1/clinicians/me/patients/{patient_id}/soap-note

    Triggers the Summarization Agent. Returns the generated SOAP note.
    """
    from app.agents.summarization.agent import SummarizationAgent, SummarizationInput

    # Verify care team assignment before running the expensive agent
    service = ClinicianService(db)
    await service.get_patient_detail(user.id, patient_id)

    rate_limit_result = await soap_note_rate_limiter.check(f"soap-note:{user.id}")
    if not rate_limit_result.allowed:
        retry_after = rate_limit_result.retry_after_seconds
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail=(
                "SOAP note generation is temporarily rate limited. "
                f"Retry after {retry_after} seconds."
            ),
            headers={"Retry-After": str(retry_after)},
        )

    agent = SummarizationAgent(db=db)
    output = await agent(
        SummarizationInput(
            user_id=user.id,
            patient_id=patient_id,
            lookback_days=request.lookback_days,
        )
    )

    return {
        "status": output.status,
        "soap_note_id": output.soap_note_id,
        "soap_note": output.soap_note,
    }


@router.post(
    "/me/patients/{patient_id}/obligations",
    response_model=ObligationRead,
    summary="Set an obligation for a patient",
    description="Clinician creates a diet, exercise, or custom obligation for a patient.",
)
async def set_patient_obligation(
    patient_id: UUID,
    data: ObligationSetRequest,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    """POST /api/v1/clinicians/me/patients/{patient_id}/obligations"""
    return await service.set_patient_obligation(user.id, patient_id, data.model_dump())


@router.post(
    "/me/patients/{patient_id}/documents/{document_id}/annotate",
    response_model=AnnotationSaveResponse,
    summary="Add clinician annotation to a document summary",
    description="Saves free-text clinician annotation alongside the AI document summary.",
)
async def annotate_document(
    patient_id: UUID,
    document_id: UUID,
    data: AnnotationCreate,
    user: CurrentUser = Depends(_clinician_dep),
    service: ClinicianService = Depends(_get_service),
) -> Any:
    """POST /api/v1/clinicians/me/patients/{patient_id}/documents/{document_id}/annotate"""
    return await service.save_document_annotation(
        user.id, patient_id, document_id, data.annotation_text
    )
