/**
 * Clinician Portal types — re-exports from @mediagent/shared.
 *
 * Import from here within the clinician portal.
 */

export type {
    LocaleMetadata,
    LocaleResourceMap,
    ClinicianPatientDocument,
    Clinician,
    Patient,
    PatientSummary,
    Medication,
    Document,
    DocumentReviewQueueItem,
    DocumentReviewer,
    ChatMessage,
    ADRAssessment,
    MedWatchDraft,
    Notification,
    Appointment,
    CareTeamMember,
    SymptomReport,
    AdherenceStats,
    FeedTask,
    FeedSummary,
    TodayFeedResponse,
    ClinicianMessage,
    Condition,
    Allergy,
    ApiErrorResponse,
    PaginatedResponse,
} from "../../../../packages/shared/src/types";

export {
    Locale,
    DEFAULT_LOCALE,
    SUPPORTED_LOCALES,
    Language,
    LOCALE_METADATA,
    getLocaleMetadata,
    getLocaleLabel,
    getLocaleSelectorLabel,
    getLocaleBadgeLabel,
    getDocumentTypeLabel,
    resolveLocaleResource,
    isLocale,
    isSpanishLocale,
    normalizeLocale,
    isLanguage,
    isSpanishLanguage,
    normalizeLanguage,
    ClinicianRole,
    PortalUserRole,
    ChatRole,
    DocumentParseStatus,
    DocumentReviewStatus,
    UploaderRole,
    NaranjoCausality,
    ADRStatus,
    MedWatchStatus,
    AppointmentStatus,
    FeedTaskStatus,
    FeedTaskType,
    NotificationType,
    MessageChannel,
    DocumentType,
    AllergySeverity,
} from "../../../../packages/shared/src/types";
