"""ADR assessment and MedWatch draft schemas."""

from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field

from app.models.enums import ADRStatus, MedWatchStatus, NaranjoCausality


class ADRAssessmentRead(BaseModel):
    """Auto-generated by Pharmacovigilance Agent using Naranjo algorithm."""

    id: UUID
    patient_id: UUID
    symptom_report_id: UUID
    suspect_medication_id: UUID
    suspect_medication_name: str  # denormalized
    naranjo_score: int = Field(..., ge=-4, le=13)
    causality: NaranjoCausality
    naranjo_answers: dict[str, str] = Field(default_factory=dict)
    naranjo_assessment: dict[str, Any] = Field(default_factory=dict)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    thinking_chain: str | None = None  # Gemini Pro thinking trace
    status: ADRStatus = ADRStatus.DRAFT
    reviewed_by: UUID | None = None
    reviewed_at: str | None = None
    dismiss_reason: str | None = None
    created_at: str


class MedWatchDraft(BaseModel):
    """FDA 3500A form fields, auto-populated from patient data."""

    id: UUID
    adr_assessment_id: UUID
    patient_id: UUID
    form_data: dict[str, Any]  # 3500A field values
    de_identified: bool = False  # PHI stripped?
    status: MedWatchStatus = MedWatchStatus.DRAFT
    submitted_at: str | None = None
    created_at: str
