"""ADR assessment, clinician review, and MedWatch draft schemas."""

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import BaseModel, Field, model_validator

from app.models.enums import ADRStatus, MedWatchStatus, NaranjoCausality


class ADRAssessmentRead(BaseModel):
    """Auto-generated by Pharmacovigilance Agent using Naranjo algorithm."""

    id: UUID
    patient_id: UUID
    symptom_report_id: UUID
    suspect_medication_id: UUID
    suspect_medication_name: str  # denormalized
    naranjo_score: int = Field(..., ge=-4, le=13)
    causality: NaranjoCausality
    naranjo_answers: dict[str, str] = Field(default_factory=dict)
    naranjo_assessment: dict[str, Any] = Field(default_factory=dict)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    thinking_chain: str | None = None  # Gemini Pro thinking trace
    status: ADRStatus = ADRStatus.DRAFT
    reviewed_by: UUID | None = None
    reviewed_at: str | None = None
    dismiss_reason: str | None = None
    created_at: str


class ADRReviewQueueItem(BaseModel):
    """Assigned-patient ADR evidence shown for clinician review.

    This intentionally excludes ``thinking_chain``. Clinicians receive the
    deterministic score inputs and patient-grounded evidence, not private model
    reasoning.
    """

    id: UUID
    patient_id: UUID
    patient_first_name: str
    patient_last_name: str
    symptom_report_id: UUID
    symptom: str
    severity: int = Field(..., ge=1, le=10)
    onset: str | None = None
    symptom_created_at: str
    suspect_medication_id: UUID
    suspect_medication_name: str
    naranjo_score: int = Field(..., ge=-4, le=13)
    causality: NaranjoCausality
    naranjo_answers: dict[str, str] = Field(default_factory=dict)
    naranjo_assessment: dict[str, Any] = Field(default_factory=dict)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    status: ADRStatus
    last_review_action: str | None = None
    review_note: str | None = None
    requested_information: list[str] = Field(default_factory=list)
    reviewed_by: UUID | None = None
    reviewed_at: str | None = None
    created_at: str


class ADRReviewQueueResponse(BaseModel):
    """Clinician-scoped ADR review queue."""

    items: list[ADRReviewQueueItem]
    total: int = Field(..., ge=0)


class ADRReviewAction(StrEnum):
    """Clinician actions supported by the ADR review queue."""

    MARK_REVIEWED = "mark_reviewed"
    DISMISS = "dismiss"
    REQUEST_INFORMATION = "request_information"


class ADRReviewDecisionRequest(BaseModel):
    """A clinician decision or information request for a draft ADR assessment."""

    action: ADRReviewAction
    note: str | None = Field(default=None, max_length=2000)
    requested_information: list[Annotated[str, Field(min_length=1, max_length=200)]] = Field(
        default_factory=list, max_length=20
    )

    @model_validator(mode="after")
    def validate_action_details(self) -> "ADRReviewDecisionRequest":
        self.note = self.note.strip() if self.note else None
        self.requested_information = list(
            dict.fromkeys(item.strip() for item in self.requested_information if item.strip())
        )
        if (
            self.action in {ADRReviewAction.DISMISS, ADRReviewAction.REQUEST_INFORMATION}
            and not self.note
        ):
            raise ValueError("A review note is required for this action")
        return self


class ADRReviewDecisionResponse(BaseModel):
    """Persisted result of an auditable clinician ADR review action."""

    id: UUID
    patient_id: UUID
    status: ADRStatus
    last_review_action: ADRReviewAction
    review_note: str | None = None
    requested_information: list[str] = Field(default_factory=list)
    reviewed_by: UUID
    reviewed_at: str
    dismiss_reason: str | None = None
    updated_at: str


class MedWatchDraft(BaseModel):
    """FDA 3500A form fields, auto-populated from patient data."""

    id: UUID
    adr_assessment_id: UUID
    patient_id: UUID
    form_data: dict[str, Any]  # 3500A field values
    de_identified: bool = False  # PHI stripped?
    status: MedWatchStatus = MedWatchStatus.DRAFT
    submitted_at: str | None = None
    created_at: str
